apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weaveworks-gitops
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      version: 4.0.34
  interval: 1m0s
  install:
    remediation:
      retries: 3
  # https://github.com/weaveworks/weave-gitops/blob/v0.35.0/charts/gitops-server/values.yaml
  values:
    adminUser:
      create: true
      username: admin
      # htpasswd -bnBC 10 "" 'password' | tr -d ':\n' | sed 's/$2y/$2a/'
      passwordHash: $2a$10$C.DJIZygnXCtKj0LCJAxz.Fxt/gNqL3AhlEUFRFxNBjxg1qY82cqe
    metrics:
      enabled: true
    ingress:
      enabled: true
      annotations:
        konghq.com/preserve-host: "true"
        konghq.com/strip-path: "true"
      className: kong
      hosts:
      - host: localhost
        paths:
        - path: /weave/*
          pathType: ImplementationSpecific
