apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weaveworks-gitops
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      version: 2.2.5
  interval: 1m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/weaveworks/weave-gitops/blob/v0.9.1/charts/gitops-server/values.yaml
  values:
    adminUser:
      create: false
    metrics:
      enabled: true
    ingress:
      enabled: true
      className: kong
      hosts:
      - host: localhost
        paths:
        - path: /weave
          pathType: ImplementationSpecific
