apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos-kube-prometheus-stack
spec:
  releaseName: thanos-kube-prometheus-stack
  chart:
    spec:
      chart: tenant
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: minio
      version: 5.0.6
  interval: 1h0m0s
  # https://github.com/minio/operator/blob/v5.0.6/helm/tenant/values.yaml
  values:
    secrets:
      name: thanos-kube-prometheus-stack
      accessKey: thanos
      secretKey: thanos
    tenant:
      name: thanos
      configuration:
        name: thanos-kube-prometheus-stack
      pools:
      - servers: 1
        name: thanos-pool-0
        volumesPerServer: 4
        size: 1Gi
        storageClassName: standard
      metrics:
        enabled: true
      buckets:
      - name: thanos-kube-prometheus-stack
