apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helmrepository.yaml
- helmrelease-crds.yaml
- helmrelease-linkerd.yaml
- helmrelease-linkerd-viz.yaml
- bundle-linkerd-identity-trust-roots.yaml
- certificate-linkerd-identity-issuer.yaml
- certificate-linkerd-trust-anchor.yaml
- clusterissuer-linkerd-self-signed-issuer.yaml
- clusterissuer-linkerd-trust-anchor.yaml

# Additional dashboards for Linkerd-Viz
# ref: https://linkerd.io/2.13/tasks/grafana/#install-grafana
# ref: https://grafana.com/orgs/linkerd/dashboards
configMapGenerator:
- name: linkerd-viz-dashboards
  namespace: linkerd-viz
  options:
    labels:
      grafana_dashboard: "1"
  files:
  - top-line=https://grafana.com/api/dashboards/15474/revisions/4/download
  - health=https://grafana.com/api/dashboards/15486/revisions/3/download
  - kubernetes=https://grafana.com/api/dashboards/15479/revisions/2/download
  - namespace=https://grafana.com/api/dashboards/15478/revisions/3/download
  - deployment=https://grafana.com/api/dashboards/15475/revisions/6/download
  - pod=https://grafana.com/api/dashboards/15477/revisions/3/download
  - service=https://grafana.com/api/dashboards/15480/revisions/3/download
  - route=https://grafana.com/api/dashboards/15481/revisions/3/download
  - authority=https://grafana.com/api/dashboards/15482/revisions/3/download
  - cronjob=https://grafana.com/api/dashboards/15483/revisions/3/download
  - job=https://grafana.com/api/dashboards/15487/revisions/3/download
  - daemonset=https://grafana.com/api/dashboards/15484/revisions/3/download
  - replicaset=https://grafana.com/api/dashboards/15491/revisions/3/download
  - statefulset=https://grafana.com/api/dashboards/15493/revisions/3/download
  - replicationcontroller=https://grafana.com/api/dashboards/15492/revisions/4/download
  - prometheus=https://grafana.com/api/dashboards/15489/revisions/2/download
  - prometheus-benchmark=https://grafana.com/api/dashboards/15490/revisions/2/download
  - multicluster=https://grafana.com/api/dashboards/15488/revisions/3/download
