apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emissary-system

# https://www.getambassador.io/docs/emissary/latest/topics/install/helm
resources:
- https://app.getambassador.io/yaml/emissary/3.7.0/emissary-crds.yaml

patches:
- path: deployment-patch.yaml
