apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: 3.10.0
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # https://github.com/kubernetes-sigs/metrics-server/blob/metrics-server-helm-chart-3.10.0/charts/metrics-server/values.yaml
  values:
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
    args:
    - "--kubelet-insecure-tls"
