apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
spec:
  releaseName: kong
  chart:
    spec:
      chart: kong
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
      version: 2.11.0
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # Default values
  # https://github.com/Kong/charts/blob/kong-2.11.0/charts/kong/values.yaml
  values:
    proxy:
      type: NodePort
      http:
        nodePort: 32080
      tls:
        nodePort: 32443
    admin:
      http:
        enabled: true
      tls:
        enabled: false
        parameters: []
