apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
spec:
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      version: v3.0.6
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # https://github.com/kyverno/kyverno/blob/kyverno-policies-chart-3.0.5/charts/kyverno/values.yaml
  values:
    grafana:
      enabled: true

    features:
      logging:
        format: json

    admissionController:
      serviceMonitor:
        enabled: true

    backgroundController:
      serviceMonitor:
        enabled: true
      rbac:
        clusterRole:
          extraResources:
          - apiGroups:
            - ""
            resources:
            - namespaces
            verbs:
            - get
            - list
            - patch
            - update
          - apiGroups:
            - batch
            resources:
            - cronjobs
            - jobs
            verbs:
            - get
            - list
            - patch
            - update

    cleanupController:
      serviceMonitor:
        enabled: true

    reportsController:
      serviceMonitor:
        enabled: true

    webhooksCleanup:
      enabled: true

    cleanupJobs:
      admissionReports:
        podAnnotations:
          linkerd.io/inject: disabled
      clusterAdmissionReports:
        podAnnotations:
          linkerd.io/inject: disabled
