apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      version: 39.1.0
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # Default values
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    # configure the alertmanager
    alertmanager:
      alertmanagerSpec:
        routePrefix: /alertmanager
      ingress:
        enabled: true
        ingressClassName: kong
        hosts:
        - localhost
        pathType: ImplementationSpecific
        paths:
        - /alertmanager(/|$)(.*)
    # configure prometheus
    prometheus:
      prometheusSpec:
        retention: 24h
        routePrefix: /prometheus
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorNamespaceSelector:
          matchLabels:
            prometheus: "yes"
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector:
          matchLabels:
            prometheus: "yes"
        probeSelectorNilUsesHelmValues: false
        probeNamespaceSelector:
          matchLabels:
            prometheus: "yes"
        ruleSelectorNilUsesHelmValues: false
        ruleNamespaceSelector:
          matchLabels:
            prometheus: "yes"
        resources:
          requests:
            cpu: 1000m
            memory: 250Mi
      ingress:
        enabled: true
        ingressClassName: kong
        hosts:
        - localhost
        pathType: ImplementationSpecific
        paths:
        - /prometheus(/|$)(.*)
    # configure grafana
    grafana:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: kong
        hosts:
        - localhost
        pathType: ImplementationSpecific
        path: /grafana(/|$)(.*)
      grafana.ini:
        server:
          domain: localhost
          root_url: http://localhost/grafana
          serve_from_sub_path: true
        users:
          viewers_can_edit: true
        auth:
          disable_login_form: true
          disable_signout_menu: true
        auth.anonymous:
          enabled: true
          org_role: Viewer
        log.console:
          format: json
    # disable scraping the controller manager
    kubeControllerManager:
      enabled: false
    # disable scraping etcd
    kubeEtcd:
      enabled: false
    # disable scraping kube-proxy
    kubeProxy:
      enabled: false
    # disable scraping the scheduler
    kubeScheduler:
      enabled: false
