# https://github.com/cilium/cilium/blob/v1.12.0/install/kubernetes/cilium/values.yaml
logOptions:
  format: json
kubeProxyReplacement: strict
k8sServiceHost: kind-control-plane
k8sServicePort: 6443
nodeinit:
  enabled: true
containerRuntime:
  integration: containerd
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
ipam:
  mode: cluster-pool

#hubble:
#  relay:
#    enabled: true
#  ui:
#    enabled: true
#    ingress:
#      enabled: true
#      annotations:
#        #konghq.com/strip-path: "true"
#        konghq.com/path: "/hubble"
#      className: kong
#      hosts:
#      - localhost
#      #path: /hubble
#
