apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  dependsOn:
  - name: namespaces
  - name: infrastructure
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kyverno-policies
  prune: true
