apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  dependsOn:
  - name: trust-manager
  - name: linkerd
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./linkerd-viz
  prune: true
