apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./linkerd
  prune: true
