apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./trust-manager
  prune: true
