apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-linkerd-disable-to-jobs
spec:
  rules:
  - name: add-linkerd-disable-to-jobs
    match:
      any:
      - resources:
          kinds:
          - CronJob
    mutate:
      patchStrategicMerge:
        spec:
          jobTemplate:
            spec:
              template:
                metadata:
                  annotations:
                    +(linkerd.io/inject): disabled
