apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- podmonitor.yaml
configMapGenerator:
- name: flux-grafana-dashboards
  namespace: prometheus-system
  files:
  - dashboards/flux-control-plane.json
  - dashboards/flux-cluster.json
  options:
    labels:
      grafana_dashboard: "1"
      app.kubernetes.io/part-of: flux
      app.kubernetes.io/component: monitoring
