apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

commonLabels:
  app.kubernetes.io/part-of: flux
  app.kubernetes.io/component: monitoring

resources:
- podmonitor.yaml

configMapGenerator:
- name: flux-grafana-dashboards
  files:
  - dashboards/flux-control-plane.json
  - dashboards/flux-cluster.json
  options:
    labels:
      grafana_dashboard: "1"
