apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  releaseName: minio
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: minio
      version: 5.0.6
  interval: 1h0m0s
  # https://github.com/minio/operator/blob/v5.0.6/helm/operator/values.yaml
  values:
    operator:
      replicaCount: 1
