apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
      version: 47.1.0
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-47.1.0/charts/kube-prometheus-stack/values.yaml
  values:
    #alertmanager:
    #  alertmanagerSpec:
    #    routePrefix: /alertmanager
    #  ingress:
    #    enabled: false
    #    ingressClassName: kong
    #    hosts:
    #    - localhost
    #    pathType: ImplementationSpecific
    #    paths:
    #    - /alertmanager(/|$)(.*)

    prometheus:
      prometheusSpec:
        retention: 24h
        #routePrefix: /prometheus
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorNamespaceSelector:
          matchLabels:
            prometheus.io/namespace.enabled: "yes"
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector:
          matchLabels:
            prometheus.io/namespace.enabled: "yes"
        probeSelectorNilUsesHelmValues: false
        probeNamespaceSelector:
          matchLabels:
            prometheus.io/namespace.enabled: "yes"
        ruleSelectorNilUsesHelmValues: false
        ruleNamespaceSelector:
          matchLabels:
            prometheus.io/namespace.enabled: "yes"
        resources:
          requests:
            cpu: 1000m
            memory: 250Mi
      #ingress:
      #  enabled: true
      #  ingressClassName: kong
      #  hosts:
      #  - localhost
      #  pathType: ImplementationSpecific
      #  paths:
      #  - /prometheus(/|$)(.*)
      thanosService:
        enabled: true
      thanosServiceMonitor:
        enabled: true
      # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#thanosspec
      thanos: {}

    thanosRuler:
      enabled: true

    grafana:
      sidecar:
        dashboards:
          searchNamespace: ALL
      enabled: true
      #ingress:
      #  enabled: false
      #  ingressClassName: kong
      #  hosts:
      #  - localhost
      #  pathType: ImplementationSpecific
      #  path: /grafana(/|$)(.*)
      grafana.ini:
        #server:
        #  domain: localhost
        #  root_url: http://localhost/grafana
        #  serve_from_sub_path: true
        users:
          viewers_can_edit: true
        auth:
          disable_login_form: true
          disable_signout_menu: true
        auth.anonymous:
          enabled: true
          org_role: Viewer
        log.console:
          format: json

    kubeProxy:
      enabled: false

    kubeControllerManager:
      enabled: false

    kubeEtcd:
      enabled: false

    kubeScheduler:
      enabled: false
