apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
      version: 47.1.0
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-47.1.0/charts/kube-prometheus-stack/values.yaml
  values:
    thanosRuler:
      enabled: true

    kubeProxy:
      enabled: false

    kubeControllerManager:
      enabled: false

    kubeEtcd:
      enabled: false

    kubeScheduler:
      enabled: false

    prometheus:
      thanosService:
        enabled: true
      thanosServiceMonitor:
        enabled: true
      prometheusSpec:
        retention: 24h
        #routePrefix: /prometheus
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorNamespaceSelector:
          matchLabels:
            prometheus.io/namespace.enabled: "yes"
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector:
          matchLabels:
            prometheus.io/namespace.enabled: "yes"
        probeSelectorNilUsesHelmValues: false
        probeNamespaceSelector:
          matchLabels:
            prometheus.io/namespace.enabled: "yes"
        ruleSelectorNilUsesHelmValues: false
        ruleNamespaceSelector:
          matchLabels:
            prometheus.io/namespace.enabled: "yes"
        resources:
          requests:
            cpu: 1000m
            memory: 250Mi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: standard
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
        disableCompaction: true
        # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#thanosspec
        # https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-47.1.0/charts/kube-prometheus-stack/values.yaml#L3329
        thanos:
          additionalArgs:
          - name: shipper.upload-compacted
          objectStorageConfig:
            name: thanos-objstore-config
            key: thanos-storage-config.yaml

    #alertmanager:
    #  alertmanagerSpec:
    #    routePrefix: /alertmanager
    #  ingress:
    #    enabled: false
    #    ingressClassName: kong
    #    hosts:
    #    - localhost
    #    pathType: ImplementationSpecific
    #    paths:
    #    - /alertmanager(/|$)(.*)

    grafana:
      sidecar:
        dashboards:
          searchNamespace: ALL
      enabled: true
      #ingress:
      #  enabled: false
      #  ingressClassName: kong
      #  hosts:
      #  - localhost
      #  pathType: ImplementationSpecific
      #  path: /grafana(/|$)(.*)
      grafana.ini:
        server:
          root_url: '%(protocol)s://%(domain)s:/'
          serve_from_sub_path: false
        users:
          viewers_can_edit: true
        auth:
          disable_login_form: true
          disable_signout_menu: true
        auth.anonymous:
          enabled: true
          org_role: Viewer
        log.console:
          format: json
