apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
      version: 47.1.0
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-47.1.0/charts/kube-prometheus-stack/values.yaml
  values:
    #alertmanager:
    #  alertmanagerSpec:
    #    routePrefix: /alertmanager
    #  ingress:
    #    enabled: false
    #    ingressClassName: kong
    #    hosts:
    #    - localhost
    #    pathType: ImplementationSpecific
    #    paths:
    #    - /alertmanager(/|$)(.*)
    prometheus:
      thanosService:
        enabled: true
      thanosServiceMonitor:
        enabled: true
      prometheusSpec:
        retention: 24h
        #routePrefix: /prometheus
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorNamespaceSelector:
          matchLabels:
            prometheus.io/namespace.enabled: "yes"
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector:
          matchLabels:
            prometheus.io/namespace.enabled: "yes"
        probeSelectorNilUsesHelmValues: false
        probeNamespaceSelector:
          matchLabels:
            prometheus.io/namespace.enabled: "yes"
        ruleSelectorNilUsesHelmValues: false
        ruleNamespaceSelector:
          matchLabels:
            prometheus.io/namespace.enabled: "yes"
        resources:
          requests:
            cpu: 1000m
            memory: 250Mi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: standard
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
        disableCompaction: true
        ## Thanos configuration allows configuring various aspects of a Prometheus server in a Thanos environment.
        ## This section is experimental, it may change significantly without deprecation notice in any release.
        ## This is experimental and may change significantly without backward compatibility in any release.
        ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#thanosspec
        ##
        #### thanos:
        ####   secretProviderClass:
        ####     provider: gcp
        ####     parameters:
        ####       secrets: |
        ####         - resourceName: "projects/$PROJECT_ID/secrets/testsecret/versions/latest"
        ####           fileName: "objstore.yaml"
        ####   objectStorageConfigFile: /var/secrets/object-store.yaml
        thanos:
          additionalArgs:
          - name: shipper.upload-compacted
          objectStorageConfig:
            name: thanos-objstore-config
            key: thanos-storage-config.yaml

      #ingress:
      #  enabled: true
      #  ingressClassName: kong
      #  hosts:
      #  - localhost
      #  pathType: ImplementationSpecific
      #  paths:
      #  - /prometheus(/|$)(.*)
      ######?????thanosService:
      ######?????  enabled: true
      ######?????thanosServiceMonitor:
      ######?????  enabled: true
      # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#thanosspec
      # https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-47.1.0/charts/kube-prometheus-stack/values.yaml#L3329

    thanosRuler:
      enabled: true

    grafana:
      sidecar:
        dashboards:
          searchNamespace: ALL
      enabled: true
      #ingress:
      #  enabled: false
      #  ingressClassName: kong
      #  hosts:
      #  - localhost
      #  pathType: ImplementationSpecific
      #  path: /grafana(/|$)(.*)
      grafana.ini:
        #server:
        #  domain: localhost
        #  root_url: http://localhost/grafana
        #  serve_from_sub_path: true
        users:
          viewers_can_edit: true
        auth:
          disable_login_form: true
          disable_signout_menu: true
        auth.anonymous:
          enabled: true
          org_role: Viewer
        log.console:
          format: json

    kubeProxy:
      enabled: false

    kubeControllerManager:
      enabled: false

    kubeEtcd:
      enabled: false

    kubeScheduler:
      enabled: false
