apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

configurations:
- kustomizeconfig.yaml

resources:
- helmrelease.yaml

secretGenerator:
- name: thanos-objstore-config
  files:
  - config/thanos-storage-config.yaml
