apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
spec:
  releaseName: keda
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: keda
      version: 2.11.1
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # Default values
  # https://github.com/kedacore/charts/blob/v2.11.1/keda/values.yaml
  values:
    logging:
      operator:
        format: json
    metricsServer:
      useHostNetwork: true
    prometheus:
      metricServer:
        enabled: true
        podMonitor:
          enabled: true
      operator:
        enabled: false
        podMonitor:
          enabled: true
        prometheusRules:
          enabled: false
