apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
spec:
  releaseName: keda
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: keda
      version: 2.12.0
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # https://github.com/kedacore/charts/blob/v2.12.0/keda/values.yaml
  values:
    asciiArt: false

    logging:
      operator:
        format: json
      webhooks:
        format: json

    certificates:
      certManager:
        enabled: true

    prometheus:
      operator:
        enabled: true
        serviceMonitor:
          enabled: true
        prometheusRules:
          enabled: true
      webhooks:
        enabled: true
        serviceMonitor:
          enabled: true
        prometheusRules:
          enabled: true
