apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  linkerd.io/inject: enabled

resources:
- prometheus.yaml
- keda.yaml
- kyverno.yaml
- emissary-system.yaml
- linkerd.yaml
- cert-manager.yaml

patches:
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: add
      path: /spec/metadata/annotations/linkerd\.io/inject
      value: enabled
