apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trust-manager
spec:
  releaseName: trust-manager
  chart:
    spec:
      chart: trust-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      version: v0.12.0
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/cert-manager/trust-manager/blob/v0.7.0/deploy/charts/trust-manager/values.yaml
  values:
    app:
      metrics:
        service:
          servicemonitor:
            enabled: true
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 16Mi
      limits:
        memory: 128Mi
    topologySpreadConstraints:
    - maxSkew: 2
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: trust-manager
