apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
spec:
  releaseName: jaeger
  chart:
    spec:
      chart: jaeger
      sourceRef:
        kind: HelmRepository
        name: jaeger
        namespace: flux-system
      version: 0.57.1
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/jaegertracing/helm-charts/blob/jaeger-0.57.1/charts/jaeger/values.yaml
  values:
    provisionDataStore:
      cassandra: false
    allInOne:
      enabled: true
      ingress:
        enabled: false
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 256m
          memory: 128Mi
      extraEnv:
      # convert CLI flag to ENV var from here: https://www.jaegertracing.io/docs/1.14/cli/#jaeger-query
      - name: QUERY_BASE_PATH
        value: /jaeger
    agent:
      enabled: false
    collector:
      enabled: false
    query:
      enabled: false
      service:
        port: 16686
      basePath: "/jaeger"
      ingress:
        enabled: true
        ingressClassName: kong
        hosts:
        - localhost
        health:
          exposed: false
