apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
spec:
  releaseName: blackbox-exporter
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
      version: 8.17.0
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # https://github.com/prometheus-community/helm-charts/blob/prometheus-blackbox-exporter-8.4.0/charts/prometheus-blackbox-exporter/values.yaml
  values:
    serviceMonitor:
      selfMonitor:
        enabled: true

    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        memory: 300Mi

    replicas: 1
    topologySpreadConstraints:
    - maxSkew: 2
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus-blackbox-exporter
          app.kubernetes.io/instance: blackbox-exporter
