apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
spec:
  releaseName: blackbox-exporter
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      version: 7.0.0
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # Default values
  # https://github.com/prometheus-community/helm-charts/blob/prometheus-blackbox-exporter-7.0.0/charts/prometheus-blackbox-exporter/values.yaml
  #values:
