apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
spec:
  releaseName: gatekeeper
  chart:
    spec:
      chart: gatekeeper
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
      version: 3.9.0
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # Default values
  # https://github.com/open-policy-agent/gatekeeper/blob/v3.9.0/charts/gatekeeper/values.yaml
  values:
    replicas: 1
    psp:
      enabled: false
