apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      version: 1.12.2
  interval: 1h0m0s
  # https://github.com/cert-manager/cert-manager/blob/v1.12.2/deploy/charts/cert-manager/values.yaml
  values:
    global:
      priorityClassName: system-cluster-critical
      leaderElection:
        namespace: cert-manager
    installCRDs: true
    namespace: cert-manager
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
